CREATE DATABASE IF NOT EXISTS GARAGEVPARROT;

CREATE TABLE IF NOT EXISTS EMPLOYES (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOM VARCHAR(32),
    PRENOM VARCHAR(32),
    EMAIL VARCHAR(128) UNIQUE NOT NULL,
    MDP VARCHAR(256) NOT NULL,
    ADMINISTRATEUR BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS VOITURES (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    MARQUE VARCHAR(32) NOT NULL,
    MODELE VARCHAR(32) NOT NULL,
    ANNEE SMALLINT NOT NULL,
    ENERGIE VARCHAR(32) NOT NULL,
    TRANSMISSION VARCHAR(32) NOT NULL,
    MOTORISATION VARCHAR(64) NOT NULL,
    IMG VARCHAR(256) NOT NULL,
    PRIX INT NOT NULL,
    KILOMETRAGE INT NOT NULL,
    PORTES INT NOT NULL,
    PLACES INT NOT NULL,
    COULEUR VARCHAR(32) NOT NULL,
    SELLERIE VARCHAR (32) NOT NULL,
    TYPES_VOITURE VARCHAR (32) NOT NULL,
    CVFISC INT NOT NULL,
    CVR INT NOT NULL
);


CREATE TABLE IF NOT EXISTS TYPES_VEHICULES (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    LIBELLE VARCHAR(32) NOT NULL,
    VOITURE_ID INT NOT NULL,
    FOREIGN KEY (VOITURE_ID) REFERENCES VOITURES (ID)
);


CREATE TABLE IF NOT EXISTS EQUIPEMENTS (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    LIBELLE VARCHAR(1024) NOT NULL,
    VOITURE_ID INT NOT NULL,
    FOREIGN KEY (VOITURE_ID) REFERENCES VOITURES (ID)
);


CREATE TABLE IF NOT EXISTS IMAGES_VOITURE (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    URL VARCHAR(1024) NOT NULL,
    NOM VARCHAR(128) NOT NULL,
    VOITURE_ID INT NOT NULL,
    FOREIGN KEY (VOITURE_ID) REFERENCES VOITURES (ID)
);

CREATE TABLE IF NOT EXISTS IMAGES (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOM VARCHAR(256) NOT NULL,
    URL VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMMENTAIRES (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    MOTIF VARCHAR(128) NOT NULL,
    NOM VARCHAR(32) NOT NULL,
    PRENOM VARCHAR(32) NOT NULL,
    EMAIL VARCHAR(128) NOT NULL,
    NOTE VARCHAR (1) NOT NULL,
    MESSAGE VARCHAR(150) NOT NULL,
    PUBLIE BOOLEAN NOT NULL
);


CREATE TABLE IF NOT EXISTS HORAIRES (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    JOUR VARCHAR(32) NOT NULL,
    MATIN VARCHAR(32) NOT NULL,
    APRESMIDI VARCHAR(32) NOT NULL
);